// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Firebase configuration for Android
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  /// Android configuration - Real Firebase Credentials
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP8ArkxYPnwhMu1n-td0LDo-bMs7pd5kQ',
    appId: '1:736610467870:android:4d0e388c5e463639b02e0f',
    messagingSenderId: '736610467870',
    projectId: 'heldoc-68abf',
    storageBucket: 'heldoc-68abf.firebasestorage.app',
  );
}
